---

#- hosts: jumpbox
#  gather_facts: false
#  roles:
#    - {name: osp-facts, when: ansible_product_name ==  'OpenStack Compute'}
# Setup front-end load balancer tier


- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - role: base-config
      tags: base-config
    - role: lb-tier
      tags: 
        - lbs
        - haproxy

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - role: base-config
      tags: base-config
    - role: app-tier
      tags: 
        - apps
        - tomcat

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - role: base-config
      tags: base-config
    - role: geerlingguy.postgresql
      tags: 
        - dbs
        - postgres

